FROM centos:centos7
COPY public/green/index.html public/index.html
COPY public/green/script.js public/script.js
COPY public/green/style.css public/style.css
COPY guestbook /usr/local/bin/guestbook
CMD ["/usr/local/bin/guestbook"]
EXPOSE 80