apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      # - image: okteto/guestbook:golang
      - image:  registry.cn-hangzhou.aliyuncs.com/haoshuwei24/guestbook:v1
        name: guestbook
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: redis

---

apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  type: NodePort
  ports:
  - name: guestbook
    port: 80
  selector:
    app: guestbook
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        selector: redis
    spec:
      containers:
        - name: redis
          image: redis:6